### ISSUE TITLE
PendingOperationButton bug

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/portal#295]
If a user is logged in as a first time user such that the `ChangePasswordModal` automatically pops up, and they try to go to an alternative route (say `/code_validations`) causing them to automatically be redirected to back to login page with the `ChangePasswordModal` popped up, and then they change their password, we get the following warning in the console:

```
react-dom.development.js:88 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in PendingOperationButton (created by ChangePasswordModalBase)
    in form (created by ChangePasswordModalBase)
```

**Comment by fordacious** [comment]
Unmounted component means it has been deleted, or is not being rendered. Generally this is a data flow issue.

**Comment by fordacious** [comment]
Based on the description I'm guessing some state change is going on in the old one referencing components that no longer exist.

**Comment by colbymorrison** [comment]
We should try and resolve this.
