### ISSUE TITLE
Refactor CSS for consistency across pages

### ISSUE THREAD

**Issue by jcolla-holla** [covidwatchorg/portal#318]
This should probably be done in `application.scss` to standardize font sizes for different elements and pages.

Note from Vic in [Figma](https://www.figma.com/file/UqWSmByDzH8k7i0PA438EP/Covid-Watch---Portal-v4-(dev)?node-id=3630%3A271869):  

"I made the fonts smaller across all of the designs. Headers, inputs, buttons, default copy, and small copy should be consistent across this new release though.

Everything was way too big before. 

Let me know if you have questions."

**Comment by aidan-fitz** [comment]
I think a better place for the styles would be `application.scss`. Then we get rid of bespoke style rules overriding the ones there unless they're absolutely necessary.
