### ISSUE TITLE
user wants to customize their organization's logo

### ISSUE THREAD

**Issue by jcolla-holla** [covidwatchorg/portal#323]
For now, Covid Watch can upload this hardcoded themselves as an MVP.  But organization X and organization Y should be able to have distinct logo images in the header.

See [Figma design](https://www.figma.com/file/UqWSmByDzH8k7i0PA438EP/Covid-Watch---Portal-v4-(dev)?node-id=0%3A1).

**Comment by aidan-fitz** [comment]
This would be on the account branding page, right? We should allow SVGs, but reject any SVG containing a `<script>` tag since they can be used to embed malicious code.
