### ISSUE TITLE
Upgrade elliptic dependency to reduce security risk

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#359]
Project depends on elliptic 6.5.2 which has a vulnerability (Integer Overflow or Wraparound in elliptic)

Upgrade dependency to latest version (6.5.3): https://www.npmjs.com/package/elliptic?activeTab=versions

**Comment by aidan-fitz** [comment]
It looks like nobody's reported this to NPM as a vulnerability. How did you find this?

**Comment by whaber** [comment]
> It looks like nobody's reported this to NPM as a vulnerability, since there's no official NPM advisory. How did you find this?

This was found via scanning with the GitLab dependency scanner.  https://docs.gitlab.com/ee/user/application_security/dependency_scanning/

**Comment by whaber** [comment]
The plot thickens. `No solution available yet.`

![image](https://user-images.githubusercontent.com/41373231/88392594-3fee8a80-cd8a-11ea-8274-93c52d9ebb74.png)

This should be fixed in the future when a solution is available.  Closing for now.

**Comment by aidan-fitz** [comment]
There's an NPM advisory now: https://www.npmjs.com/advisories/1547
