### ISSUE TITLE
Upgrade dependency for yargs-parser to reduce security risk

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#361]
Upgrade yargs-parser to latest version to reduce security risk.

Current version (10.1.0) has vulns including  Improper Input Validation in yargs-parser 

Latest version is 18.1.3: https://www.npmjs.com/package/yargs-parser

**Comment by aidan-fitz** [comment]
Looks like we've got four different versions of `yargs-parser` installed: `18.1.3`, `9.0.2`, `10.1.0`, `13.1.2`.
