### ISSUE TITLE
Upgrade dependency serialize-javascript to reduce security risk

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#362]
Upgrade package dependency for serialize-javascript as current version in use (2.1.2) has a high severity security vulnerability for injection.

Latest version is 4.0.0: https://www.npmjs.com/package/serialize-javascript

**Comment by ibeckermayer** [comment]
This is in our `package-lock.json`, meaning that some other library that we're using depends on it. In that case, I think we just have to live with this vulnerability, since that library is expecting 2.x.x.

**Comment by colbymorrison** [comment]
I believe this is no longer an issue. The security vulnerabilities were for versions <3.1.0, which we no longer have in our package-lock.json.

<img width="1275" alt="Screen Shot 2020-08-27 at 11 56 58 AM" src="https://user-images.githubusercontent.com/20446774/91483352-71141c00-e85c-11ea-8f9a-02b4cb15b4ae.png">
