### ISSUE TITLE
Security: API key detected in code

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#368]
If this should not be exposed, please change the key and do not place the key in public areas of GitHub.

apiKey - firebase.config.local.js

**Comment by colbymorrison** [comment]
See the comment at the top of firebase.config.dev.js for an explanation about these Firebase "API keys." If I remember correctly, they are not actually used for authentication and are ok to have in public GitHub.

**Comment by jcolla-holla** [comment]
Perhaps that same message should be added to `firebase.config.local.js` and any other locations where a firebase API key is included.
