### ISSUE TITLE
Fix radio buttons on Safari

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/portal#409]
Users on Catalina/Safari are getting this:
![image](https://user-images.githubusercontent.com/13578537/88544952-40845c80-cfe8-11ea-9bc9-f8f169d6d7d4.png)

On Mojave/Safari, it looks better but appears not to be picking up the custom styling:

Safari (no custom styling)
<img width="500" alt="Screen Shot 2020-07-27 at 9 06 28 AM" src="https://user-images.githubusercontent.com/13578537/88545215-ac66c500-cfe8-11ea-9615-d34ae9938cae.png">

Brave (expected styling):
<img width="510" alt="Screen Shot 2020-07-27 at 9 09 01 AM" src="https://user-images.githubusercontent.com/13578537/88545338-da4c0980-cfe8-11ea-922a-632eb69eec0e.png">

**Comment by colbymorrison** [comment]
For me, the buttons look the same on Safari as other platforms

### Linux / Firefox
![DeepinScreenshot_Navigator_20200805113525](https://user-images.githubusercontent.com/20446774/89450917-382ad080-d710-11ea-84ac-a1fbb3e7d61d.png)

**Comment by kyle-mcr** [comment]
Merge #466
