### ISSUE TITLE
Calendar input api not working on Safari

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/portal#410]
On Brave, the "Symptom Onset Date" is the inbuilt calendar input element:
<img width="541" alt="Screen Shot 2020-07-27 at 9 18 02 AM" src="https://user-images.githubusercontent.com/13578537/88546259-1c297f80-cfea-11ea-9990-1925e76f01d7.png">

However on Safari, users can input whatever they want into that box
<img width="551" alt="Screen Shot 2020-07-27 at 9 14 09 AM" src="https://user-images.githubusercontent.com/13578537/88546124-ef756800-cfe9-11ea-95a9-24306bc0e6dc.png">

<img width="559" alt="Screen Shot 2020-07-27 at 9 17 27 AM" src="https://user-images.githubusercontent.com/13578537/88546196-074cec00-cfea-11ea-95f0-8f7f96e3e36a.png">

**Comment by colbymorrison** [comment]
Safari doesn't support a date picker :( 

https://stackoverflow.com/questions/35682138/html5-date-picker-doesnt-show-on-safari
