### ISSUE TITLE
X-Content-type-options allows older browsers to perform MIME-sniffing

### ISSUE THREAD

**Issue by whaber** [covidwatchorg/portal#424]
To solve, change the headers to add:
`X-Content-Type-Options: nosniff`

Ref: https://owasp.org/www-community/Security_Headers

**Comment by ibeckermayer** [comment]
@whaber I assume these are headers in our calls to Firebase Cloud Functions (all of our outgoing traffic is to those). According to [this SO answer](https://stackoverflow.com/questions/59411126/how-to-add-headers-to-firebase-httpscallable-function), we can't do anything about this...

**Comment by whaber** [comment]
This is lower priority due to only impacting older browsers.  I am ok with closing it if it is easy (or not possible) to remediate.
