### ISSUE TITLE
Use Cache-Control in the HTTP headers (or use http-equiv in the HTML) to make screen short-lived on staging

### ISSUE THREAD

**Issue by ibeckermayer** [covidwatchorg/portal#444]
For example (seconds, so 10 minutes)

`Cache-Control: max-age=600`

This way users won't typically need to remember to hard-refresh in order to get the updated version of the app

**Comment by jcolla-holla** [comment]
So after some testing, this actually doesn't appear to be an issue.  After merging a PR into our staging branch `dev` and then loading the staging site (which I've loaded many times in this browser and has at least some cached images, etc), the version of the site that loaded included the PR code.  

[This video shows this](https://www.loom.com/share/bf6a2884a7d44a94aa62c8c95148e183).  Skip ahead to 3:10 to see this (no audio on this video)
