### ISSUE TITLE
No validation message is displayed and code is generated when user is deleting month or date section

### ISSUE THREAD

**Issue by jcolla-holla** [covidwatchorg/portal#489]
No validation message is displayed and code is generated when user is deleting month or date section.

Asana link [here](https://app.asana.com/0/1188301658055194/1188793474409842/f) with more details on how to reproduce.  If you need access to Asana let me know.

**Comment by colbymorrison** [comment]
When the user deletes a month or date section, the date is interpreted as an empty string. We allow a code to be generated with just a diagnosis selection and no date, which I think is correct. So for the system, this is the same case (diagnosis selected and no date). 

So, if we should leave the date as optional what should the semantics be in this case?
